{
 "title": "Camel",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Camel Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(CamelMessageHistory_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Exchanges Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "CamelExchangesTotal_total" }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "jvm_classes_loaded_classes" }
   ]
  },
  {
   "title": "Tomcat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "tomcat_sessions_created_sessions_total"
    }
   ]
  }
 ]
}