{
 "title": "MAPS Rejections and Validations",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "channelType",
    "label": "Channel Type",
    "query": {
     "query": "label_values(maps_route_end_seconds_count, channelType)"
    }
   },
   {
    "name": "paymentSystemId",
    "label": "Payment System",
    "query": {
     "query": "label_values(maps_route_end_seconds_count, paymentSystemId)"
    }
   },
   {
    "name": "connectionId",
    "label": "Connection Id",
    "query": {
     "query": "label_values(maps_route_end_seconds_count, connectionId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rejections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rejections Rate By Channel Type",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (channelType,rejectionCode) (irate(maps_route_end_seconds_count{channelType=~\"${channelType}\", messageType=\"message_reject\"}[5m]))",
     "legendFormat": "{{channelType}}:{{rejectionCode}}"
    }
   ]
  },
  {
   "title": "Rejections Rate By Channel Type and Connection Id",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (paymentSystemId,connectionId,channelType,rejectionCode) (irate(maps_route_end_seconds_count{\n    channelType=~\"${channelType}\", \n    connectionId=~\"${connectionId}\", \n    messageType=\"message_reject\"}[5m]))",
     "legendFormat": "{{channelType}}:{{connectionId}}:{{rejectionCode}}"
    }
   ]
  },
  { "title": "Validations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Validation Rate By Channel Type",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (channelType,txStatus) (irate(maps_route_end_seconds_count{routeId=\"LEG_4\",channelType=~\"${channelType}\"}[5m]))",
     "legendFormat": "{{channelType}}:{{txStatus}}"
    }
   ]
  },
  {
   "title": "Validation Rate By Channel Type and Payment System and Connection Id ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (paymentSystemId,connectionId,channelType,txStatus) (irate(maps_route_end_seconds_count{\n    routeId=\"LEG_4\",\n    paymentSystemId=~\"${paymentSystemId}\",\n    channelType=~\"${channelType}\",\n    connectionId=~\"${connectionId}\"}[5m]))",
     "legendFormat": "{{channelType}}:{{paymentSystemId}}:{{connectionId}}:{{txStatus}}"
    }
   ]
  }
 ]
}