{
 "title": "middleware",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "rabbitmq",
    "label": "RabbitMq",
    "query": {
     "query": "label_values(rabbitmq_queue_messages_published_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Inbound Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_queue_messages_published_total{queue=~\".*req\\\\.from\\\\.maps.*\", instance=~\"${rabbitmq}\"}[5m]))",
     "legendFormat": "Number of Inbound Request Published"
    }
   ]
  },
  {
   "title": "Inbound Request UnProcessed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{queue=~\".*req\\\\.from\\\\.maps.*\", instance=~\"${rabbitmq}\"})",
     "legendFormat": "Number of Inbound Request Unprocessed"
    }
   ]
  },
  {
   "title": "Outbound Response Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_queue_messages_published_total{queue=~\".*resp\\\\.to\\\\.maps.*\", instance=~\"${rabbitmq}\"}[5m]))",
     "legendFormat": "Number of Outbound Response Published"
    }
   ]
  },
  {
   "title": "Outbound Response Unprocessed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{queue=~\".*resp\\\\.to\\\\.maps.*\", instance=~\"${rabbitmq}\"})",
     "legendFormat": "Number of OutBound Response Unprocessed"
    }
   ]
  },
  {
   "title": "T-Log Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_queue_messages_published_total{queue=~\".*-TLOG-.*\", instance=~\"${rabbitmq}\"}[5m]))",
     "legendFormat": " Number of T-Log Published"
    }
   ]
  },
  {
   "title": "T-Log Unprocessed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{queue=~\".*-TLOG-.*\", instance=~\"${rabbitmq}\"})",
     "legendFormat": "Number of T-Log Unprocessed"
    }
   ]
  },
  {
   "title": "N-Log Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_queue_messages_published_total{queue=~\".*-nlog-.*\", instance=~\"${rabbitmq}\"}[5m]))",
     "legendFormat": " Number of N-Log Published"
    }
   ]
  },
  {
   "title": "N-Log Unprocessed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{queue=~\".*-nlog-.*\", instance=~\"${rabbitmq}\"})",
     "legendFormat": "Number of N-Log Unprocessed"
    }
   ]
  },
  {
   "title": "Raw-Log Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_queue_messages_published_total{queue=~\".*-rawlog-.*\", instance=~\"${rabbitmq}\"}[5m]))",
     "legendFormat": "Number of Raw-Log Published"
    }
   ]
  },
  {
   "title": "Raw-Log Unprocessed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{queue=~\".*-rawlog-.*\", instance=~\"${rabbitmq}\"})",
     "legendFormat": "Number of Raw-Log Unprocessed"
    }
   ]
  }
 ]
}