{
 "title": "Perimeter Service",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(ps_gateway_seconds_count, application)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ps_gateway_seconds_count{application=~\"$application\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(route, status) ( \n  irate(ps_gateway_seconds_count{application=~\"$application\", job=~\"$job\"}[5m]) \n)",
     "legendFormat": "{{status}} {{route}}"
    }
   ]
  },
  {
   "title": "Gateway Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by(route, status) ( \n  irate(ps_gateway_seconds_sum{application=~\"$application\", job=~\"$job\"}[5m])\n  /\n  irate(ps_gateway_seconds_count{application=~\"$application\", job=~\"$job\"}[5m]) \n)",
     "legendFormat": "{{status}} {{route}}"
    }
   ]
  },
  {
   "title": "Duplicate Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(transaction_duplicates_total{application=~\"$application\", job=~\"$job\"}[5m]))",
     "legendFormat": "duplicate rate"
    }
   ]
  },
  {
   "title": "Timed Out Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(transaction_timeouts_total{application=~\"$application\", job=~\"$job\"}[5m]))",
     "legendFormat": "timed out transaction rate"
    }
   ]
  }
 ]
}