{
 "title": "RabbitMQ Client",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(rabbitmq_consumed_total, instance)"
    }
   },
   {
    "name": "connectionFactory",
    "label": "Connection Factory",
    "query": {
     "query": "label_values(rabbitmq_consumed_total, connectionFactory)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumed (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_consumed_total{instance=\"$instance\", connectionFactory=~\"$connectionFactory\"}[5m])",
     "legendFormat": "{{connectionFactory}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connections{instance=\"$instance\", connectionFactory=~\"$connectionFactory\"}",
     "legendFormat": "{{connectionFactory}}"
    }
   ]
  },
  {
   "title": "Published (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_published_total{instance=\"$instance\", connectionFactory=~\"$connectionFactory\"}[5m])",
     "legendFormat": "{{connectionFactory}}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_channels{instance=\"$instance\", connectionFactory=~\"$connectionFactory\"}",
     "legendFormat": "{{connectionFactory}}"
    }
   ]
  },
  {
   "title": "Failed to Publish (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_failed_to_publish_total{instance=\"$instance\", connectionFactory=~\"$connectionFactory\"}[5m])",
     "legendFormat": "{{connectionFactory}}"
    }
   ]
  },
  {
   "title": "Acknowledged (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_acknowledged_total{instance=\"$instance\", connectionFactory=~\"$connectionFactory\"}[5m])",
     "legendFormat": "{{connectionFactory}}"
    }
   ]
  },
  {
   "title": "Rejected (5m rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_rejected_total{instance=\"$instance\", connectionFactory=~\"$connectionFactory\"}[5m])",
     "legendFormat": "{{connectionFactory}}"
    }
   ]
  }
 ]
}