{
 "title": "Spring Data Repository",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_sum, instance)"
    }
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_sum, repository)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_sum{repository=\"$repository\"}, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", method=~\"$method\",repository=~\"$repository\",state=\"SUCCESS\"}[10s]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Average Exec Time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(spring_data_repository_invocations_seconds_sum{instance=\"$instance\", method=~\"$method\",repository=~\"$repository\",state=\"SUCCESS\"}[10s]) / irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", method=~\"$method\",repository=~\"$repository\",state=\"SUCCESS\"}[10s])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds{instance=\"$instance\", method=~\"$method\",repository=~\"$repository\",state=\"SUCCESS\",quantile=\"0.9\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds{instance=\"$instance\", method=~\"$method\",repository=~\"$repository\",state=\"SUCCESS\",quantile=\"0.99\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Max Exec Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_max{instance=\"$instance\", method=~\"$method\",repository=~\"$repository\",state=\"SUCCESS\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}