server:
    port: 8080

    tomcat:
        threads:
            max: 50
            min-spare: 2
        max-connections: 10

camel:
    servlet:
        mapping:
            context-path: /services/*
    springboot:
        routes-include-pattern: classpath:camel-routes/*
    thread-pool:
        pool-size: 5
        config:
            max-pool-size: 5
            pool-size: 5
    component:
        rabbitmq:
            prefetchEnabled: true
            prefetchGlobal: false
            prefetchSize: 0
            prefetchCount: 1


jss:
    camel:
        hello:
            enabled: false
        seda:
            enabled: false
        file:
            enabled: false
        rabbitmq:
            enabled: false
        wiretap:
            enabled: false
        rest:
            enabled: false
        rest-dsl:
            enabled: false
        rest-metrics:
            enabled: false
        kafka:
            enabled: false
        error-handlers:
            enabled: false
        jms:
            enabled: false
        testcontainers:
            enabled: false
        saga:
            enabled: false

metrics: 0 */1 * * * *

logging:
    level:
        root: INFO
        org.apache.camel: INFO
        com.jss.camel.components: INFO
        org.apache.http: INFO
        org.apache.commons.httpclient: INFO
        org.apache.coyote: INFO

---
spring:
    config:
        activate:
            on-profile: management

management:
    health:
        rabbit:
          enabled: false
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    endpoints:
        web:
            exposure:
                include:
                    - info
                    - health
                    - prometheus
                    - liveness
    endpoint:
        health:
            show-details: never
            probes:
                enabled: true

            group:
                readiness:
                    include: "*"