

server:
    port: 8081

    tomcat:
        threads:
            max: 50
            min-spare: 2
        max-connections: 10

camel:
    servlet:
        mapping:
            context-path: /services/*
    springboot:
        routes-include-pattern: classpath:camel-routes/*
    thread-pool:
        pool-size: 5
        config:
            max-pool-size: 5
            pool-size: 5
    component:
        rabbitmq:
            prefetchEnabled: true
            prefetchGlobal: false
            prefetchSize: 0
            prefetchCount: 1

jss:
    camel:
        hello:
            enabled: false
        seda:
            enabled: false
        file:
            enabled: false
        rabbitmq:
            enabled: true
        rabbitmq-throttler:
            enabled: false
        wiretap:
            enabled: false
        rest-java-dsl:
            enabled: false
        #Weather
        rest-dsl:
            enabled: false
        rest-dsl-rabbit:
            enabled: true
        rest-metrics:
            enabled: false
        kafka:
            enabled: false
        error-handlers:
            enabled: false
        jms:
            enabled: false
        testcontainers:
            enabled: false
        saga:
            enabled: false
        circuit-breaker:
            enabled: false

metrics: 0 */1 * * * *

logging:
    level:
        root: INFO
        org.apache.camel: INFO
        com.jss.camel.components: INFO
        org.apache.http: INFO
        org.apache.commons.httpclient: INFO
        org.apache.coyote: INFO

spring:
    profiles:
        include: management

---
spring:
    config:
        activate:
            on-profile: management

management:
    health:
        rabbit:
          enabled: false
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    endpoints:
        web:
            exposure:
                include:
                    - info
                    - health
                    - prometheus
                    - liveness
                    - metrics
                    - micrometer-camel-message-history
                    - caches
                    - loggers
                    - startup-properties
                    - startup-state
    endpoint:
        health:
            show-details: "ALWAYS"
            probes:
                enabled: true
    metrics:
        data:
            repository:
                autotime:
                    percentiles-histogram: true
                    percentiles: 0.5, 0.75, 0.9, 0.99
        distribution:
            percentiles:
                CamelRoutePolicy: 0.5, 0.75, 0.9, 0.99
            percentiles-histogram:
                camelRoutePolicy: true
#    endpoint:
#        health:
#            show-details: never
#            probes:
#                enabled: true
#
#            group:
#                readiness:
#                    include: "*"